name: Convert Jupyter Notebooks to HTML files

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ipynb'

jobs:
  convert-to-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert beautifulsoup4

      - name: Convert Notebooks to HTML and Preserve Folder Structure
        run: |
          find . -name '*.ipynb' | while read notebook; do
            html_path="${notebook%.ipynb}.html"
            dir_path=$(dirname "$html_path")
            mkdir -p "docs/$dir_path"
            jupyter nbconvert --to html "$notebook" --output "docs/$html_path"
          done

      - name: Run write_to_index.py
        run: python write_to_index.py

      - name: Commit and push HTML files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Update HTML files" -a || echo "No changes to commit"
          git push
