name: Convert Jupyter Notebooks to HTML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ipynb'

jobs:
  convert-to-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Convert Notebooks to HTML
        run: |
          mkdir -p docs
          find . -name '*.ipynb' -exec jupyter nbconvert --to html {} \;
          find . -name '*.html' -exec mv {} docs/ \;

      - name: Commit and push HTML files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/*.html
          git commit -m "Update HTML files" -a || echo "No changes to commit"
          git push
